config/routes.rb
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  # get 'stores/index'
  # get 'stores/show'
  # get 'stores/new'
  # get 'stores/edit'
  # get 'stores/daily_report'
  devise_for :admin_users
  devise_scope :admin_user do
    root 'devise/sessions#new'
  end
  resources :stores do
    member do
      post :daily_report,:monthly_report
      get :delete, :daily_report ,:monthly_report, :yearly_report
      
    end  
  end
  # get 'csv_transaction_details', to: 'csv_transaction_details#new'
  # post 'csv_transaction_details', to: 'csv_transaction_details#create'
   resources  :store_transactions do

    collection {post :import}
    
    end
 

end

app/models/store.rb
class Store < ApplicationRecord

    has_many :store_transactions , dependent: :destroy 

    scope :sorted,lambda { order ("id ASC")}
    validates_presence_of :store
    validates_length_of :store, :maximum => 255
    validates_presence_of :city
    validates_length_of :city, :maximum => 25
    
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  layout "store"
  

  def index
    @stores=Store.sorted
  end

  def show
    @store=Store.find(params[:id])
    
    @store_transactions = @store.store_transactions.page(params[:page] )  
  end

  def new
    @store=Store.new
  end

  def create
    @store=Store.new(store_params)
    if @store.save
      flash[:notice]="Store created successfully"
      redirect_to(stores_path)
    else
      render('new')
    end
  end

  def edit
    @store=Store.find(params[:id])

  end

  def update
    @store=Store.find(params[:id])
    
    if @store.update_attributes(store_params)
      flash[:notice]="Store updated successfully"
      redirect_to(stores_path)
    else 
      render('edit')
    end
  end

  # def delete
  #   @store=Store.find(params[:id])
  # end

  # def destroy
  #   @store=Store.find(params[:id])
  #   @store.destroy
  #   flash[:notice]="Store'#{@store.store_name}' deleted successfully"
  #   redirect_to(stores_path)
  # end
  def daily_report
    @store=Store.find(params[:id])
    @date = params[:day]|| Date.today
    @daily_reports=  @store.store_transactions.joins(:store).order(date: :desc).select("card_type ","name","card_colour","amount","date","store_name","tid","txn_id","store_id").where("DATE(date) = ?", @date)
   
  
    respond_to do |format|
      format.html{ @daily_reports = @daily_reports.page(params[:page]) }
      format.csv {send_data  to_csv(@daily_reports)  , filename: "daily report-#{Date.today}.csv"}
    end
  end
  def monthly_report
    @store=Store.find(params[:id])
    @month=params[:month] 
    
    @monthly_reports=  @store.store_transactions.joins(:store).select("date","store_name","tid","status","card_type","card_network","amount","CASE WHEN card_type='Credit' AND (card_network='VISA'OR card_network='MASTERCARD') THEN 2.00 WHEN card_type='Debit' AND amount<2000 
    AND (card_network='VISA'OR card_network='MASTERCARD')THEN 0.45 WHEN card_type='Debit' AND amount>2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN 0.95 ELSE  0.00  END AS store_mdr",
    "CASE WHEN card_type='Credit' AND (card_network='VISA'OR card_network='MASTERCARD')
    THEN ((amount*2.00)/100) WHEN card_type='Debit' AND amount<2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN ((amount*0.45)/100)
    WHEN card_type='Debit' AND amount>2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN ((amount*0.95)/100) ELSE ((amount*0.00)/100) END AS new_amount",
    "CASE WHEN card_type='Credit' AND (card_network='VISA'OR card_network='MASTERCARD')
    THEN ((amount*2.00*18)/(100*100)) WHEN card_type='Debit' AND amount<2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN ((amount*0.45*18)/(100*100))
    WHEN card_type='Debit' AND amount>2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN ((amount*0.95*18)/(100*100)) ELSE ((amount*0.00*18)/(100*100)) END AS gst_amount",
    "CASE WHEN card_type='Credit' AND (card_network='VISA'OR card_network='MASTERCARD')
    THEN (amount-((amount*2.00)/100)-((amount*2.00*18)/(100*100))) WHEN card_type='Debit' AND amount<2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN (amount-((amount*0.45)/100)-((amount*0.45*18)/(100*100)))
    WHEN card_type='Debit' AND amount>2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN (amount-((amount*0.95)/100)-((amount*0.95*18)/(100*100))) ELSE (amount-((amount*0.00)/100)-((amount*0.00*18)/(100*100))) END AS total_amount",
    "acquirer").where("to_char(date, 'YYYY-MM')=?",@month)

    @amount_sum  = @monthly_reports.sum(:amount)
    @new_amount  = @monthly_reports.sum(:"CASE WHEN card_type='Credit' AND (card_network='VISA'OR card_network='MASTERCARD')
    THEN ((amount*2.00)/100) WHEN card_type='Debit' AND amount<2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN ((amount*0.45)/100)
    WHEN card_type='Debit' AND amount>2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN ((amount*0.95)/100) ELSE ((amount*0.00)/100) END ")
    @gst= @monthly_reports.sum(:"CASE WHEN card_type='Credit' AND (card_network='VISA'OR card_network='MASTERCARD')
    THEN ((amount*2.00*18)/(100*100)) WHEN card_type='Debit' AND amount<2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN ((amount*0.45*18)/(100*100))
    WHEN card_type='Debit' AND amount>2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN ((amount*0.95*18)/(100*100)) ELSE ((amount*0.00*18)/(100*100)) END ")
    @payable_amount= @monthly_reports.sum(:"CASE WHEN card_type='Credit' AND (card_network='VISA'OR card_network='MASTERCARD')
    THEN (amount-((amount*2.00)/100)-((amount*2.00*18)/(100*100))) WHEN card_type='Debit' AND amount<2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN (amount-((amount*0.45)/100)-((amount*0.45*18)/(100*100)))
    WHEN card_type='Debit' AND amount>2000 AND (card_network='VISA'OR card_network='MASTERCARD') THEN (amount-((amount*0.95)/100)-((amount*0.95*18)/(100*100))) ELSE (amount-((amount*0.00)/100)-((amount*0.00*18)/(100*100))) END" )
    
    respond_to do |format|
      format.html{ @monthly_reports = @monthly_reports.page(params[:page]) }
      format.csv {send_data as_csv(@monthly_reports)  , filename: "monthly report-#{Date.today}.csv"}
    end

  end
  # def yearly_report
  #   @store=Store.find(params[:id])
  #   @yearly_reports=  @store.store_transactions.joins(:store).select("card_type ","name","card_colour","amount","date","store_name","tid","txn_id","store_id")
  #   @amount_sum  =  @yearly_reports.sum(:amount)


  # end
  

  private

  def store_params
    params.require(:store).permit(:store_name,:city)
  end


  def to_csv (daily_reports)
    
   

    CSV.generate(headers: true) do |csv|
      csv <<[ "Store ID", "Store Name" , "TID" , "Txn ID", "Name", "Card Type", "Card colour", "Amount", "Date"]

        daily_reports.all.each do |daily_report|

            csv<<[
            daily_report.store_name,
            # store.city,
            daily_report.tid,
            daily_report.store_id,
            daily_report.txn_id,
            daily_report.name,
            daily_report.card_type,
            daily_report.card_colour,
            daily_report. amount,
            daily_report.date,
          
          ]
        end
      end
  end
  def as_csv (monthly_reports)
   
   

    CSV.generate(headers: true) do |csv|
        csv <<["Date","Store Name", "TID#",  "Status", "Card Type", "Brand Type", "Amount", "Store MDR", "Amount","GST","Store Payable", "Acquring Bank"]

        monthly_reports.each do |monthly_report|

            csv<<[
              monthly_report.date,
              monthly_report.store_name,
              monthly_report.tid,
              monthly_report.status,
              monthly_report.card_type,
              monthly_report.card_network,
              monthly_report.amount,
              monthly_report.store_mdr,
              monthly_report.new_amount,
              monthly_report.gst_amount,
              monthly_report.total_amount,
              monthly_report.acquirer

            
          
         ]
        end
      end
      
  end
  
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/stores/_form.html.erb
<table summary="Store form filed">
  <tr>
    <th class="column" >STORE &nbsp;&nbsp;</th>
    <td class="column"><%= f.text_field :store_name, required: true, :size=>"32"%></td>
  </tr>
  <tr>
    <th class="column">CITY</th>
    <td class="column"><%= f.text_field :city,required: true%></td>
  </tr>
  <tr>
   
  
</table>
<!-- <div class="show_table">
  <div class="table-row">
     <div class="table-cell column">STORE &nbsp;&nbsp; </div>
     <div class="table-cell column"><%= f.text_field :store_name, required: true, :size=>"32"%></div>
  </div><br>
  <div class="table-row">
     <div class="table-cell column">CITY</div>
     <div class="table-cell column"><%= f.text_field :city,required: true%></div>
  </div>
</div> -->

app/views/stores/daily_report.html.erb
<br>
<%=link_to image_tag("/assets/back.png", size:"30x30"),store_path,class:'btn back',role:'button'%>
<center><h3 class="daily_Report_heading" >Daily Report</h3></center> 
<!-- <br><br><br><br><br><br> --><br><br>
<center>
<div class="card  filter" style="width: 650px;">
    
    <div class="card-body">
      
 <%= form_with  url:daily_report_store_url, local: true ,html: {class: "date_form"}  do |form| %>
    <%= form.date_field :day  , class:"form",required: true,label: 'Select Date'%>&nbsp;&nbsp;
<%= form.submit "FILTER", class:"daily_report_submit"  %>
<% end %>
              
    </div>
</div></center>
  <br><br><br><br>
  <form class="d-flex daily_search">
     <input  onkeyup="searchStore()" id="searchbar" class="form-control me-2" type="search" placeholder="Search" aria-label="Search"></form>
<%=link_to image_tag("/assets/data-transfer-download.png" ,height:"20px", width:"20px", class:"download")+" Export to CSV",daily_report_store_path(format: :csv, params: params.to_unsafe_h),class:"btn daily_report",role:'button'%>
<br>
  <div class="row justify-content-center ">
    <div class="col-auto index-table">
   
<div class="table-responsive">   
   
<table class="table table-hover table-borderless  daily_report_table" id="table_id" summary="Store list">

    <tr class="header">
        <th scope="col" class="col">Store ID</th>
        <th scope="col" class="col">Store Name</th>
        <th scope="col"class="col">TID</th>
        <th scope="col" class="col">Txn ID</th>
        <th scope="col" class="col">Name</th>
        <th scope="col" class="col">Card Type</th>
        <th scope="col" class="col">Card Color</th>
        <th scope="col" class="col">Amount</th>
        <th scope="col" class="col">Date</th>
        
    </tr>
    
    <%if @daily_reports.empty? %>
        <tr>
            <td colspan="9" scope="row" class="blank">No result found</td>
        </tr>
    <% else %>
        <% @daily_reports.each do |daily_report| %>
        <tr>
            <td scope="row"><%=daily_report.store_id %></td>
            <td scope="row"><%=daily_report.store_name %></td>
            <td scope="row"><%=daily_report.tid %></td>
            <td scope="row"><%=daily_report.txn_id %></td>
            <td scope="row"><%=daily_report.name%></td>
            <td scope="row"><%=daily_report.card_type %></td>
            <td scope="row"><%=daily_report.card_colour %></td>
            <td scope="row"><%=daily_report.amount %></td>
            <td scope="row"><%=daily_report.date%></td>
        </tr>
        <%end%>
    <%end%>
    
  
    
    

</table>
&nbsp;&nbsp;&nbsp;
    
    <!-- <div class="seconddiv"><br><div class="filter-heading"><center>FILTER</center></div><br>
        <form class="d-flex ">
        &nbsp;&nbsp; <input  onkeyup="searchStore()" id="searchbar" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        </form><br>&nbsp;
        <button onclick="document.getElementById('id01').style.display='block'" class="w3-button w3-black select_date">Search by Date</button>
    
        <div id="id01" class="w3-modal">
            <div class="w3-modal-content w3-animate-zoom modal_content">
              <header class="w3-container w3-teal"> 
                
                <div class="modal-today" ><%=Date.today.to_s(:long)%><br><center>
                    <image src="/assets/calendar.png", height="120px",width="100px"></center></div>
                
                
                <div class="modal_date">
                <%= form_with  url:daily_report_store_url, local: true ,html: {class: "date_form"}  do |form| %>
                <%= form.date_field :day  , class:"form",required: true%> 
                <%= form.submit "OK", class:"submit"  %>
              <% end %><span  style="color:black" onclick="document.getElementById('id01').style.display='none'" 
        class="w3-button w3-display-topright">&times;</span></div>
            
          </div></div>
    </div> -->
    </div></div></div>
<br>
<div class="paginate">
    <%= paginate  @daily_reports , theme: 'bootstrap-5',
    pagination_class: "pagination-sm flex-wrap justify-content-center",
    nav_class: "d-inline-block"%>
</div>

app/views/stores/delete.html.erb
<%= link_to("<< Back to List",stores_path, :class=> 'back-link') %>
<div class="stores delete">
  <h2>Delete Store</h2>
  <%= form_for(@store, :method=> 'delete') do |f| %>
  <p>Are you sure you permanenetly delete the store?</p>
  <p class="reference name"><%=@store.store_name%></p>
  <div class="form buttons"><%=f.submit("Delete Store")%></div>
  <% end%>
</div>

app/views/stores/edit.html.erb
<br>
<%=link_to image_tag("/assets/back.png", size:"30x30"),store_path,class:'btn back',role:'button'%>
<center>
<div class="edit-store">
  <h2>Edit Store</h2><br>
  <%=form_for @store  do |f|%>
  <%=render(:partial =>'form',:locals=>{:f=>f})%><br>
  <!-- <div class="form-buttons"><%= f.submit"Update Store",class:"button"%></div> -->
  <%= f.submit"Update Store",class:"btn button", type:"submit" %>
  <% end%>

</div><br>

<!-- <%=link_to image_tag("/assets/back.png", border: 0,size:"50x50"),store_path%> </center> -->
<!-- <%=link_to("Back to store list",stores_path)%> -->

app/views/stores/index.html.erb
<br>

<center><h3 >STORES</h3></center><br>
<div class="Store index"><br>
    <br><br><br>
    
   <div class="index_button"> 
    <%=link_to"Create new store",new_store_path,id:'create-store',class:'btn create-store me-md-2',role:'button'%>
    <%=link_to"UPLOAD CSV FILE",store_transactions_path,id:'csv-upload',class:'btn csv-upload',role:'button'%>
   </div>
    <!-- <button type="button" class="btn create-store" ><%=link_to"Create new store",new_store_path,id:'create-store'%></button> -->
    <!-- <button type="button" class="btn csv-upload" ><%=link_to"UPLOAD CSV FILE",store_transactions_path,id:'csv-upload'%></button> -->
    <!-- <image src="/assets/search.png", heignt="30px", width="30px", alt="serach", class="index-search"> -->
    <form class="d-flex search">
    <input  onkeyup="searchStore()" id="searchbar" class="form-control me-2 index-search" type="search" placeholder="Search" aria-label="Search">
    </form>

   
    <div class="row justify-content-center ">
    <div class="col-auto">
    <div class="table-responsive">
    <table class="table table-hover table-borderless table-responsive" id="table_id"  summary="Store list">
        <tr class="header">
            <th scope="col" class="col">Store ID</th>
            <th scope="col" class="col">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Store Name</th>
            <th scope="col" class="col">&nbsp;&nbsp;&nbsp;&nbsp;City</th>
        </tr>
        <% @stores.each do |store| %>
        <tr>
            <td scope="row"><%=store.id%></td>
            <td scope="row"><%=link_to store.store_name,store_path(store), id:'show'%></td>
            <td scope="row"><%=store.city%></td>
           
            
        </tr>
        <%end%>
    </table>
</div></div>

    </div>
</div>

app/views/stores/monthly_report.html.erb
<br>
<%=link_to image_tag("/assets/back.png", size:"30x30"),store_path,class:'btn back',role:'button'%>

<center><h3 class="daily_Report_heading" >Monthly Report</h3></center>
<br><br><br>
<center>
<div class="card filter" style="width: 650px;">
    
    <div class="card-body">
      
        <%= form_with  url:monthly_report_store_url, local: true,html: {class: "date_form"}  do |form| %>
        <%= form.month_field :month , class:"form",required: true %> 
        <%= form.submit  "OK", class:"monthly_report_submit"  %>
        
         <% end %> 
              
    </div>
</div>
</center>
<br><br><br><br>
<form class="d-flex daily_search">
     <input  onkeyup="searchStore()" id="searchbar" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
    </form>
<%=link_to image_tag("/assets/data-transfer-download.png" ,height:"20px", width:"20px", class:"download")+" Export to CSV",monthly_report_store_path(format: "csv" , params: params.to_unsafe_h),class:"btn monthly_report",role:'button'%><br>

        <div class="row justify-content-center ">
            <div class="col-auto index-table">
                <div class="table-responsive">  
   
<table class="table table-hover table-borderless monthly_report_table table-responsive" id="table_id" summary="Store list">

<tr class="header">
    <th scope="col" class="col">Trans_date</th>
    <th scope="col" class="col">Store </th>
    <th scope="col" class="col">TID#</th>
    <th scope="col" class="col">Store Type</th>
    <th scope="col" class="col">Counter</th>
    <th scope="col" class="col">Status</th>
    <th scope="col" class="col">Mode</th>
    <th scope="col" class="col">Card Type</th>
    <th scope="col" class="col">Brand Type</th>
    <th scope="col" class="col">Amount</th>
    <th scope="col" class="col">Store MDR</th>
    <th scope="col" class="col">Amount</th>
    <th scope="col" class="col">GST</th>
    <th scope="col" class="col">Store Payabale</th>
    <th scope="col" class="col">Acquring Bank</th>
    
</tr>
<%if @monthly_reports.empty? %>
<tr>
    <td colspan="15" scope="row" class="blank">No result found</td>
</tr>
<% else %>
<% @monthly_reports.each do |monthly_report| %>
<tr>
    <td scope="row"><%=monthly_report.date %></td>
    <td scope="row"><%=monthly_report.store_name %></td>
    <td scope="row"><%=monthly_report.tid %></td>
    <td scope="row">Others</td>
    <td scope="row"></td>
    <td scope="row"><%=monthly_report.status %></td>
    <td scope="row">Card</td>
    <td scope="row"><%=monthly_report.card_type %></td>
    <td scope="row"><%=monthly_report.card_network %></td>
    <td scope="row"><%=monthly_report.amount %></td>
    <td scope="row"><%=monthly_report.store_mdr %></td>
    <td scope="row"><%=monthly_report.new_amount %></td>
    <td scope="row"><%=monthly_report.gst_amount %></td>
    <td scope="row"><%=monthly_report.total_amount %></td>
    <td scope="row"><%=monthly_report.acquirer %></td>

        

        
</tr>

<%end%>
<tr>
    <td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td><h5>Total</h5></td>
    <td scope="row"><h5><%=@amount_sum%></h5></td>
    <td></td><td><h5><%=@new_amount%></h5></td><td><h5><%=@gst%></h5></td><td><h5><%=@payable_amount%></h5></td><td></td>
</tr>
<%end%>

<!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->
</table>
&nbsp;&nbsp;&nbsp;
<!-- <div class="seconddiv"><br><div class="filter-heading"><center>FILTER</center></div><br>
        <form class="d-flex ">
        &nbsp;&nbsp; <input  onkeyup="searchStore()" id="searchbar" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        </form><br>&nbsp;
        <button onclick="document.getElementById('id01').style.display='block'" class="w3-button w3-black select_date">Search by Date</button>
    
        <div id="id01" class="w3-modal">
            <div class="w3-modal-content w3-animate-zoom modal_content">
              <header class="w3-container w3-teal"> 
                <div class="modal-today" ><%=Date.today.to_s(:long)%><br><center>
                    <image src="/assets/calendar.png", height="120px",width="100px"></center></div>
                        
                
                        <div class="modal_month">
                <%= form_with  url:monthly_report_store_url, local: true,html: {class: "date_form"}  do |form| %>
        <%= form.month_field :month , class:"form",required: true %> 
        <%= form.submit  "OK", class:"submit"  %>
        
         <% end %> 
     <span style="color:black" onclick="document.getElementById('id01').style.display='none'" 
    class="w3-button w3-display-topright">&times;</span></div>
</div></div>
</div> -->
</div></div></div>
<br>
    <div class="paginate">
    <%= paginate @monthly_reports ,theme: 'bootstrap-5',
pagination_class: "pagination-sm flex-wrap justify-content-center",
nav_class: "d-inline-block" %>
    </div>

app/views/stores/new.html.erb
<br>
<%=link_to image_tag("/assets/back.png", size:"30x30"),stores_path,class:'btn back',role:'button'%>
<center>
<div class="new-store">
  <h2>New Store</h2><br>
  <%=form_for(@store,:url=>stores_path,:method => 'post') do |f|%>
  <%=render(:partial =>'form',:locals=>{:f=>f})%><br>
  <!-- <div class="form-buttons"><%= f.submit "Create Store",class:"button"%></div> -->
  <%= f.submit "Create Store",class:"btn button", type:"submit"%>
  <% end%>

</div><br>
<!-- <%=link_to image_tag("/assets/back.png", border: 0,size:"50x50"),stores_path%> </center> -->
</center>

app/views/stores/show.html.erb
<br>
<%=link_to image_tag("/assets/back.png", size:"30x30"),stores_path,class:'btn back',role:'button'%>

<!-- <button class="back"><%=link_to("Back",stores_path)%></button> -->
<center><h3 >STORE &nbsp;DETAILS</h3></center>
<div class="show_button">
<%=link_to"Edit",edit_store_path(@store),class:'btn edit',role:'button'%>
<br><br>
<div class="show-dropdown"><label class=" dropdown" >

  <div class="dd-button">
   Reports
  </div>

  <input type="checkbox" class="dd-input" id="test">

  <ul class="dd-menu">
    <li>
      <%=link_to"Daily Report",daily_report_store_path%>
      <%=link_to"Monthly Report",monthly_report_store_path%>
    </li>
  </ul>
  
</label>

</div></div>

<center>
<div class="show_table">
    <div class="table-row">
       <div class="table-cell">STORE &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;</div>
       <div class="table-cell"><%=@store.store_name%></div>
    </div><br>
    <div class="table-row">
       <div class="table-cell city-column">CITY</div>
       <div class="table-cell"><%=@store.city%></div>
    </div>
 </div>
</center><br>
<!-- <image src="/assets/search.png", heignt="30px", width="30px", alt="serach", class="search-icon"> -->
    <!-- <form class="d-flex show-search">
    <input  onkeyup="searchStore()" id="searchbar" class="form-control me-2 " type="search" placeholder="Search" aria-label="Search">
    </form> -->
   <br>
<div class="row justify-content-center ">
    <div class="col-auto">
      <div class="table-responsive">
<table class="table table-hover table-borderless table-responsive" id="show_table" summary="Store list">
<tr class="header">
    <th scope="col" class="col">Acquirer</th>
    <th scope="col" class="col">TID</th>
    <th scope="col" class="col">POS</th>
    <th scope="col"class="col">MID</th>
    <th scope="col" class="col">Batch no</th>
    <th scope="col" class="col">Card no</th>
    <th scope="col" class="col">Name</th>
    <th scope="col" class="col">Card Issuer</th>
    <th scope="col" class="col">Card Type</th>
    <th scope="col" class="col">Card Colour</th>
    <th scope="col" class="col">txn_id</th>
    <th scope="col" class="col">Invoice</th>
    <th scope="col" class="col">Date</th>
</tr>

<% @store_transactions.each do |store_transaction| %>
    <tr>
        <td scope="row"><%=store_transaction.acquirer%></td>
        <td scope="row"><%=store_transaction.tid%></td>
        <td scope="row"><%=store_transaction.pos%></td>
        <td scope="row"><%=store_transaction.mid%></td>
        <td scope="row"><%=store_transaction.batch_no%></td>
        <td scope="row"><%=store_transaction.card_no%></td>
        <td scope="row"><%=store_transaction.name%></td>
        <td scope="row"><%=store_transaction.card_issuer%></td>
        <td scope="row"><%=store_transaction.card_type%></td>
        <td scope="row"><%=store_transaction.card_colour%></td>
        <td scope="row"><%=store_transaction.txn_id%></td>
        <td scope="row"><%=store_transaction.invoice%></td>
        <td scope="row"><%=store_transaction.date%></td>
        </td>
     </tr>
   
<%end%>

   
</table>
      </div> </div></div><br>
    <div class="paginate">
    <%= paginate @store_transactions, theme: 'bootstrap-5',
    pagination_class: "pagination-sm flex-wrap justify-content-center",
    nav_class: "d-inline-block "
    %>
    </div>
    
    


  