config/routes.rb
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  # get 'stores/index'
  # get 'stores/show'
  # get 'stores/new'
  # get 'stores/edit'
  # get 'stores/daily_report'
  devise_for :admin_users
  devise_scope :admin_user do
    root 'devise/sessions#new'
  end
  resources :stores do
    member do
      post :daily_report,:monthly_report
      get :delete, :daily_report ,:monthly_report, :yearly_report
      
    end  
  end
  # get 'csv_transaction_details', to: 'csv_transaction_details#new'
  # post 'csv_transaction_details', to: 'csv_transaction_details#create'
   resources  :store_transactions do

    collection {post :import}
    
    end
 

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MDRProgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/layouts/store.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MDR Program</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" 
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= stylesheet_link_tag    'store', media: 'all', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
   
    <nav class="navbar store-navbar navbar-fixed-top">
      <div class="navbar-header pull-left"> <h5 class="navbar-brand nav-heading"><b>MDR REPORT</b></h5></div>
      <div class="navbar-header pull-right">
       <div class="home "><%= link_to "Home",stores_path, class:"navbar-brand"%></div> 
  
               <div class="signout  "><%= link_to "Sign out",destroy_admin_user_session_path, :method => :delete, class:"navbar-brand" %></div> </div>
      
    </nav>
    
    <!-- before -->
    <%= yield %>
    <!-- after -->
    <%= javascript_include_tag 'store', 'data-turbolinks-track': 'reload' %>
    
  </body>
</html>